# version: "3.9"

services:
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile.mariadb
      args:
        TZ: ${TZ}
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      TZ: ${TZ}
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
    volumes:
      - mariadb-phpmyadmin-vol:/var/lib/mysql
      - ./mariadb/conf.d:/etc/mysql/conf.d:ro
      - ./mariadb/mariadb.conf.d:/etc/mysql/mariadb.conf.d:ro
      - ./mariadb/mariadb.cnf:/etc/mysql/mariadb.cnf:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mariadb-admin ping -h 127.0.0.1 -uroot -p$${MARIADB_ROOT_PASSWORD} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [mariadb-phpmyadmin-net]

  phpmyadmin:
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile.phpmyadmin
      args:
        TZ: ${TZ}
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_DB_PORT}
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}
      PMA_ARBITRARY: "0"
      PMA_BLOWFISH_SECRET: ${PMA_BLOWFISH_SECRET}
      TZ: ${TZ}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
    ports:
      - "${PMA_PORT}:80"
    networks: [mariadb-phpmyadmin-net]

networks:
  mariadb-phpmyadmin-net:

volumes:
  mariadb-phpmyadmin-vol:
